# Generated by Django 5.1.3 on 2024-11-23 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AlgerianCities',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Nom de la ville')),
            ],
            options={
                'db_table': 'algerian_cities',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Lieux',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Agence')),
                ('address', models.CharField(max_length=255, verbose_name='Adresse')),
                ('lieu_type', models.CharField(choices=[('airport', 'Aéroport'), ('office', 'Bureau')], max_length=20, verbose_name='Type de lieu')),
                ('mobile', models.CharField(max_length=20, verbose_name='Mobile')),
            ],
            options={
                'db_table': 'lieux',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nom de la zone')),
            ],
            options={
                'db_table': 'zone',
                'managed': False,
            },
        ),
    ]
