# Generated by Django 5.1.3 on 2024-11-23 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='zone',
            options={},
        ),
    ]
