# Generated by Django 5.1.3 on 2024-11-23 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_zone_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='algeriancities',
            options={},
        ),
        migrations.AlterModelOptions(
            name='lieux',
            options={},
        ),
    ]
