# Generated by Django 5.0.6 on 2024-11-24 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_algeriancities_options_alter_lieux_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='algeriancities',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='lieux',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='zone',
            options={'managed': False},
        ),
    ]
